name: mneme
description: Open-source mobile app for memorizing poetry using Spaced Repetition and Offline Speech Recognition
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/icon_fg.png"
  android: "launcher_icon"
  ios: false
  macos: 
    generate: false
  web:
    generate: false
  windows:
    generate: false
