name: mneme
description: Open-source mobile app for memorizing poetry using Spaced Repetition and Offline Speech Recognition
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.2.0
  crypto: ^3.0.7
  drift: ^2.20.3
  drift_flutter: ^0.2.2
  es_compression: ^2.0.15
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  sqlite3_flutter_libs: ^0.5.41


dev_dependencies:
  archive: ^4.0.8
  args: ^2.6.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.20.3
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/database/

flutter_launcher_icons:
  image_path: "assets/images/icon_fg.png"
  android: "launcher_icon"
  ios: false
  macos: 
    generate: false
  web:
    generate: false
  windows:
    generate: false
